# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCobra < Formula
  desc "Hello, world! sample of Cobra in Golang."
  homepage "https://github.com/KEINOS/Hello-Cobra/"
  version "1.3.4"

  on_macos do
    url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.4/Hello-Cobra_1.3.4_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "2ae81a3606ed668abda6e178e211023cb9fb665caf4128139eb3ab6a606ad839"

    def install
      bin.install "hello-cobra"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.4/Hello-Cobra_1.3.4_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "0afa000668f573d9ce563638b4677cf7dbf17a0fa7ea68a2086393c97c29e7cc"

      def install
        bin.install "hello-cobra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.4/Hello-Cobra_1.3.4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0e4f9f6a6fefe9747e0751262526c2be9ddacdf4ae9ed173f82f11bdc195b1ef"

      def install
        bin.install "hello-cobra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.4/Hello-Cobra_1.3.4_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "327671496ddce7d3cb101b69adec013b3717e87f5fa20a1daef1c37e6c1e142e"

      def install
        bin.install "hello-cobra"
      end
    end
  end

  test do
    system "#{bin}/hello-cobra --version"
  end
end
