# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCobra < Formula
  desc "Hello, world! sample of Cobra in Golang."
  homepage "https://github.com/KEINOS/Hello-Cobra/"
  version "1.3.2-alpha"

  on_macos do
    url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.2-alpha/Hello-Cobra_1.3.2-alpha_macOS_all.zip", :using => CurlDownloadStrategy
    sha256 "4af0365c37f677359befe9443676eba42ab06b3f143d8f39db6487394de4aa32"

    def install
      bin.install "hello-cobra"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.2-alpha/Hello-Cobra_1.3.2-alpha_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "9554d3d580433a029293beb0d45fa2506af3fd45744121bcf9766ed565519bc6"

      def install
        bin.install "hello-cobra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.2-alpha/Hello-Cobra_1.3.2-alpha_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2837521c9ff4447edb4ac43e035195ec40d0d8fd17e0555e7961202db225daba"

      def install
        bin.install "hello-cobra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KEINOS/Hello-Cobra/releases/download/v1.3.2-alpha/Hello-Cobra_1.3.2-alpha_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "95b0417f9836f92dad1631c9355f2730635495ad01c8436646e578208145a472"

      def install
        bin.install "hello-cobra"
      end
    end
  end

  test do
    system "#{bin}/hello-cobra --version"
  end
end
